name: Melon Ticket Notifier

on:
  workflow_dispatch:
    inputs:
      product-id:
        description: "Melon Product ID (예: 204755)"
        required: true
      schedule-id:
        description: "Schedule ID"
        required: true
      seat-id:
        description: "Seat ID (예: 1_0)"
        required: true
      message:
        description: "Slack message"
        required: false
        default: "티켓사세요"

jobs:
  check-ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ✅ 루트를 가리키도록 변경
      - name: Run local action
        uses: ./
        with:
          product-id: ${{ github.event.inputs.product-id }}
          schedule-id: ${{ github.event.inputs.schedule-id }}
          seat-id: ${{ github.event.inputs.seat-id }}
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: ${{ github.event.inputs.message }}

      # (디버그용) 문제 생기면 주석 해제해 파일 구조 확인
      # - run: |
      #     pwd
      #     ls -la
