name: Melon Ticket Notifier

on:
  workflow_dispatch:
    inputs:
      product-id:
        description: "Melon Product ID (예: 204755)"
        required: true
      schedule-id:
        description: "Schedule ID"
        required: true
      seat-id:
        description: "Seat ID (예: ST0001 / R001 / 1_0 등)"
        required: true
      message:
        description: "Slack message"
        required: false
        default: "티켓사세요"

jobs:
  check-ticket:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # ✅ 내 리포의 패치된 코드 실행 (업스트림 X)
      - name: Run local action
        uses: ./
        env:
          # ✅ GitHub Secrets 에 저장한 쿠키를 ENV 로 전달
          MELON_COOKIE: ${{ secrets.MELON_COOKIE }}
        with:
          product-id: ${{ github.event.inputs.product-id }}
          schedule-id: ${{ github.event.inputs.schedule-id }}
          seat-id: ${{ github.event.inputs.seat-id }}
          slack-incoming-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          message: ${{ github.event.inputs.message }}

      # (선택) 디버그: 쿠키가 전달됐는지 길이만 출력
      # - name: Debug cookie presence
      #   run: |
      #     echo "MELON_COOKIE length: ${#MELON_COOKIE}"
      #   env:
      #     MELON_COOKIE: ${{ secrets.MELON_COOKIE }}
